name: Template Sync

on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: OGCraftMC/Datapack-Template
          upstream_branch: main  # change if not main
          pr_labels: teplate_sync
